User and Character API endpoints
Dagonite6/dndlocal pull request #3
Opened 2023-04-09 16:07 UTC by Dagonite6

Register User (POST Request): <br>
```localhost/auth/register/``` <br>
Login (POST Request): <br>
```localhost/auth/login``` <br>
Logout (POST Request): <br>
```localhost/auth/logout``` <br>

<br>

Create character (POST Request): <br>
```localhost/character/create``` <br>
List of characters (GET request): <br>
```localhost/character/``` <br>
Update character (PUT/PATCH requests): <br>
```localhost/character/<ID>``` <br>
Delete character (DELETE request): <br>
```localhost/character``` <br>

2023-04-09 16:59 UTC, fedoroko requested changes

2023-04-09 16:59 UTC, fedoroko commented on backend/backend/urls.py
> +
комментирование кода плохая практика, если не используется - удаляй

2023-04-09 16:59 UTC, fedoroko commented on backend/character/__pycache__/views.cpython-39.pyc
кеш в игнор https://stackoverflow.com/questions/3719243/best-practices-for-adding-gitignore-file-for-python-projects

2023-04-09 16:59 UTC, fedoroko commented on backend/character/migrations/0007_alter_character_items_alter_character_spells.py
не критично, но много alter'ов в таблицах, они в общем-то не нужны сейчас, т.к. у нас пока нет данных, можно просто удалить содержимое папки миграций и сделать makemigrations

2023-04-09 16:59 UTC, fedoroko commented on backend/character/models.py
> +# Create your models here.
ненужный коммент

2023-04-09 16:59 UTC, fedoroko commented on backend/character/models.py
> +    char_class = models.PositiveSmallIntegerField()
давай расе и классу тоже default=0, индексация рас и классов все равно будет с 1, 0 будет значить невыбранное значение

2023-04-09 16:59 UTC, fedoroko commented on backend/character/models.py
> +    param_value = models.CharField(max_length=200)
вообще 200 маловато, тут может быть предыстория на 5 а4 листов, давай тут сделаем TextField без ограничения

2023-04-09 16:59 UTC, fedoroko commented on backend/character/serializers.py
> +            raise serializers.ValidationError({"class": "Class overflow."})
чуть поменяем:
race == 0 - empty race
race > MAX_RACE - unknown race

аналогично для класса

2023-04-10 10:00 UTC, fedoroko requested changes

2023-04-10 10:00 UTC, fedoroko commented on backend/character/serializers.py
> +        raise serializers.ValidationError({"class": "Unknown class"})
убрать вложенность, как обсуждали

2023-04-10 10:00 UTC, fedoroko commented on backend/character/urls.py
> +    path('<int:pk>/', views.DetailView.as_view(), name='Details'), #на один эндпоинт у нас get, patch, put и delete реквесты
pk можно переименовать в id

2023-04-10 10:50 UTC, Dagonite6 commented on backend/character/urls.py
> +    path('<int:pk>/', views.DetailView.as_view(), name='Details'), #на один эндпоинт у нас get, patch, put и delete реквесты
Не можно, pk это то как джанго понимает что надо айдишник уникальный использовать, и во всех примерах как айди в базе в ссылке указывается pk. Eсли переименовать в айди надо потом во вью ему указывать lookup_url_kwarg - The URL keyword argument that should be used for object lookup. Лишний код во вьюве, если бы у нас параметр в ссылке был именем то тогда стоило бы, а так и то ито одно и тоже значит.

2023-04-10 11:10 UTC, fedoroko approved these changes

2023-04-10 11:11 UTC, merged